### ISSUE TITLE
Possibility To Render Address Suggestion Box Elsewhere / Not At All

### ISSUE THREAD

**Issue by sprankhub** [netresearch/postdirekt-autocomplete-monorepo#1]
I know that my requirements might be "special". However, I still hope that you are willing to help :joy: 

I currently integrate this library in Hyvä Checkout. Hyvä Checkout uses Magewire (Livewire for Magento). The address suggestions are initially shown as expected. However, they are removed very soon, because Hyvä Checkout has an auto-save feature, which then leads to a complete re-rendering of the address form. So what happens is the following:

1. User starts typing :+1: 
2. Suggestion box is shown :+1: 
3. Auto-save is triggered :+1: 
4. Magewire re-renders the whole address form removing the suggestion box :-1: 

I didn't find any viable solution to change this and even the creator of Magewire could not really suggest anything. I compared it with the Google Maps autocomplete, which doesn't have this issue. The difference is that Google Maps inserts the suggestion box not directly inside the address form, but somewhere completely else in the body (it's just appended to the body tag). It is then simply absolutely positioned. So my question to you guys is: Are you open to not inserting the suggestion box directly next to the respective input field, but simply appending it to the body instead (at least optionally)? This should be the right place to change this behaviour:

https://github.com/netresearch/postdirekt-autocomplete-monorepo/blob/ec82f65d7572efb189cc7b8300c932995ff08113/packages/autocomplete-library/src/view/list-renderer.ts#L54

Another option would be to dispatch an event with the suggest box HTML (or just the suggestions) and not adding it to the DOM at all (of course, also optionally).

What do you think?

Thanks in advance!

**Comment by powli** [comment]
Hey @sprankhub, thanks for the suggestion. The library code is currently being used in the Magento1 and Magento2 as well as the Shopware6 extension. That and a lack of resources for implementation and testing make me not very eager to change the basic working principle in this case.
However, if listening for an **added** event with the Datalist HTML would solve your use case, we would not be opposed to adding that. If you can provide a PR with an implementation that suits your needs, we'll review it in a timely manner ;)

**Comment by sprankhub** [comment]
Alright, I'm done with this, @powli. Here are my PRs:

1. #2: This was necessary, so that I could work on this. Otherwise, I directly got an error during the build process.
2. #3: This is what we discussed in this issue. It introduces a new event dispatched when new suggestions are retrieved.
3. #4: This is what I also suggested. You didn't say no, so I hope you'll include this ;) This makes life a bit easier if people want to render suggestions themselves, which they can as soon as #3 is merged.

Thanks for your support!

**Comment by Sebastian80** [comment]
Hi @sprankhub , thank's for your contribution. We will review your PRs in the comming two weeks (approx).
We can not give you a dedicated timeframe, but we try our best to get this through as fast as possible.

**Comment by powli** [comment]
Hey @sprankhub, sorry for the wait. I merged all your PRs through our internal repo. It took a bit longer as I decided to migrate this library to Github only for the future to make it easier to maintain.

:information_source: Slight adjustment on my side for #3: The event gets triggered on the `document` object instead of the `window` object to stay consistent with the rest of the code base.

**Comment by sprankhub** [comment]
Thank you for your help, @powli!

**Comment by powli** [comment]
@sprankhub for the changes to take effect in your M2 installation you will want to use the [browser-dropins.zip](https://github.com/netresearch/postdirekt-autocomplete-monorepo/releases/download/1.3.0/browser-dropins.zip) from the release and replace [the according files in the M2 integration](https://github.com/netresearch/deutschepost-module-autocomplete-m2/tree/master/view/frontend/web/js/lib) (at least until the patch release comes out ;))

**Comment by powli** [comment]
Updated M2 Module: https://github.com/netresearch/deutschepost-module-autocomplete-m2/releases/tag/1.4.3
